title: لنتعلم معاً برمجة الأنظمة المدمجة
email: kalhabish@gmail.com
repository: "kalhabish/kalhabish.github.io"
author: خالد الغامدي
lang: ar-SA
locale: ar-SA
dir: rtl
description: "خسائر اللازمة ومطالبة حدة بل. الآخر الحلفاء أن غزو, إجلاء وتنامت عدد مع. لقهر معركة لبلجيكا، بـ انه, ربع الأثنان المقيتة في, اقتصّت المحور حدة و. هذه ما طرفاً عالمية استسلام, الصين وتنامت حين ٣٠, ونتج والحزب المذابح كل جوي. أسر كارثة المشتّتون بل, وبعض وبداية الصفحة غزو قد, أي بحث تعداد الجنوب"

# User/Organization page
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://kalhabish.github.io" 
# or url: "https://kalhabish.com" if you have a custom domain name

# Project page
baseurl: "/embedded_course" # the subpath of your site, e.g. /blog
url: "https://kalhabish.github.io/embedded_course" # the base hostname & protocol for your site, e.g. http://example.com

# According to
# https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/
#baseurl: "/embedded_course"
#url: "https://kalhabish.github.io"

twitter_username: alhabish
github_username:  alhabish
linkedin_account: "khalid-alghamidi-59657962"
google_analytics: UA-106201878-1
show_downloads: false

# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
theme: jekyll-theme-minimal
#plugins:
#  - jekyll-feed

#baseurl: "/minimal-mistakes"
#url: "https://mmistakes.github.io"  

