title: أنظمة مدمجة
email: kalhabish@gmail.com
author: خالد الغامدي
lang: ar_SA
locale: ar_SA
dir: rtl
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: alhabish
github_username:  alhabish
show_downloads: true
google_analytics:

#twitter:
#  username: alhabish
  
# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  



#baseurl: "/jekyll-for-designers" 
#url: "http://jameswillweb.github.io/jekyll-for-designers" 

